# Generated by Django 4.1.5 on 2023-01-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cnab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=1)),
                ('data', models.CharField(max_length=10)),
                ('valor', models.CharField(max_length=256)),
                ('cpf', models.CharField(max_length=14)),
                ('cartao', models.CharField(max_length=12)),
                ('hora', models.CharField(max_length=8)),
                ('dono_da_loja', models.CharField(max_length=14)),
                ('nome_da_loja', models.CharField(max_length=19)),
            ],
        ),
    ]
