# Generated by Django 4.1.5 on 2023-01-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNAB_PARSE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnab',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=256),
        ),
    ]
