# Generated by Django 4.1.5 on 2023-01-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNAB_PARSE', '0002_alter_cnab_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnab',
            name='data',
            field=models.DateField(max_length=10),
        ),
    ]
